# docker-compose.yml
services:
    server:
        image: express-docker
        ports:
            - 5050:5000
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client:/app'
            - '/app/node_modules'
        ports:
            - 8080:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
    mongodb:
        image: mongo
