# docker-compose.yml
services:
    server:
        build: ./server
        ports:
            - 5050:5000
        command: npm run dev
        volumes:
            - ./server/src/:/app/src/
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client:/app'
            - '/app/node_modules'
        ports:
            - 8080:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
    mongodb:
        image: mongo
        volumes:
            - ./data:/data/db
